# Generated by Django 4.0.8 on 2022-10-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ststus', models.CharField(max_length=500)),
                ('Audit_Requests', models.CharField(max_length=500)),
                ('Date_Requested', models.DateField()),
                ('Due_date', models.DateField()),
                ('Client_contact', models.EmailField(max_length=254)),
                ('Date_Received', models.DateField()),
                ('Other_Comments', models.CharField(max_length=500)),
                ('WT_Comment', models.CharField(max_length=500)),
                ('Select', models.BooleanField(default=False, verbose_name='Select')),
            ],
        ),
    ]
