# Generated by Django 4.0.8 on 2022-10-19 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='General',
            new_name='General_Models',
        ),
    ]
