# Generated by Django 4.0.8 on 2022-10-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0002_rename_general_general_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_models',
            name='Other_Comments',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='general_models',
            name='WT_Comment',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
