# Generated by Django 4.0.8 on 2022-10-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0003_alter_general_models_other_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_models',
            name='Client_contact',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='general_models',
            name='Date_Received',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='general_models',
            name='Date_Requested',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='general_models',
            name='Due_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='general_models',
            name='Ststus',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
