# Generated by Django 4.0.8 on 2022-10-19 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0004_alter_general_models_client_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='general_models',
            old_name='Ststus',
            new_name='Status',
        ),
    ]
