# Generated by Django 4.0.8 on 2022-10-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0006_alter_general_models_client_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_models',
            name='Client_contact',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
